# -*- coding: utf-8 -*-
"""Combat Online Plagiarism with AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPpGaigmOPcXmx1K4nKfuZVtDJspFhYz
"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter

nltk.download('punkt')
nltk.download('stopwords')

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(text.lower())
    filtered_words = [word for word in words if word.isalnum() and word not in stop_words]
    return filtered_words

def calculate_similarity(text1, text2):
    words1 = preprocess_text(text1)
    words2 = preprocess_text(text2)
    counter1 = Counter(words1)
    counter2 = Counter(words2)
    common_words = set(words1) & set(words2)
    total_words = sum(counter1.values()) + sum(counter2.values())
    if total_words == 0:
        return 0
    else:
        return len(common_words) / total_words

def detect_plagiarism(original_text, suspicious_texts, similarity_threshold=0.7):
    plagiarized_texts = []
    for text in suspicious_texts:
        similarity = calculate_similarity(original_text, text)
        if similarity >= similarity_threshold:
            plagiarized_texts.append((text, similarity))
    return plagiarized_texts

# Input from user
original_text = input("Enter the original text: ")

num_suspicious_texts = int(input("Enter the number of suspicious texts: "))
suspicious_texts = []
for i in range(num_suspicious_texts):
    text = input(f"Enter suspicious text {i+1}: ")
    suspicious_texts.append(text)

# Detect plagiarism
plagiarized_texts = detect_plagiarism(original_text, suspicious_texts)
if plagiarized_texts:
    print("Plagiarized texts found:")
    for text, similarity in plagiarized_texts:
        print(f"- Similarity: {similarity:.2f}, Text: {text}")
else:
    print("No plagiarized texts found.")